language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
  - gem install bundler
script:
- gem install bundler
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
 deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   access_key_id: $AWS_ACCESS_KEY_ID 
   secret_access_key: $AWS_SECRET_ACCESS_KEY
   app: cappua-be
   env: Cappuabe-env
   bucket_name: "elasticbeanstalk-us-east-2-882396049373"
   run: rails db:migrate
